//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity6_10
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebOrder
    {
        public int OrderId { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool isDeleted { get; set; }
        public decimal Amount { get; set; }
    }
}
